trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Build

name: 2.3.$(BuildID)

steps:
- checkout: self
  clean: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'AspNetCore.MongoDb.sln'
    arguments: '-c Release -p:PackageVersion=$(Build.BuildNumber)'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: 'Release'
    includesymbols: true
    includesource: true
    versioningScheme: 'byBuildNumber'
    verbosityPack: 'Normal'
- task: NuGetCommand@2
  displayName: Publish
  inputs:
    command: push
    feedsToUse: 'config'
    includeNugetOrg: true
    publishFeedCredentials: NuGet
    packagesToPack: dist\*.nupkg