trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: major
  value: 6
- name: minor
  value: 0
- name: revCounter
  value: $[counter(format('{0}.{1}-{2}', variables['major'], variables['minor'], variables['build.sourceBranchName']), 0)]
- name: rev
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    value: $[format('.{0}', variables['revCounter'])]
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    value: $[format('-{0}{1}', variables['build.sourceBranchName'], variables['revCounter'])]
- group: Build

name: $(major).$(minor)$(rev)

steps:
- checkout: self
  clean: true
- task: UseDotNet@2
  inputs:
    version: '5.0.x'
    includePreviewVersions: false
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'AspNetCore.MongoDb.sln'
    arguments: '-c Release -p:PackageVersion=$(Build.BuildNumber)'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: 'src/**/*.csproj'
    configuration: 'Release'
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: 'byBuildNumber'
    verbosityPack: 'Normal'
- task: NuGetCommand@2
  displayName: Push
  condition: and(contains(variables['build.sourceBranch'], 'refs/heads/master'), succeeded())
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'